## Script to execute all analyses in the appropriate order for the sierra 
## density analysis

## Most packages necessary are installed through the environment.yml file. There are three
## additional packages that need to be installed manually

install.packages("brms", version="2.16.3")
install.packages("patchwork", version="1.1.1")
install.packages("mltools", version="0.3.5")

### Explore which sites have candidate failed invasions

### NOTE: We provide the datasets generated by this script that are necessary to reproduce
### the results int he analysis, but we do not provide the entirety of the 
### Rana sierra dataset (i.e., >9000 lakes) with this submission.  As such, `make_candidate_failed_invasions.Rmd`
### and `build_data_sets.R` do not have the necessary data to be run. However, all the `analysis*` files
### can be executed with the intermediate data provided.

# Build R script

knitr::purl("make_candidate_failed_invasions.Rmd")

# Source R script
source("make_candidate_failed_invasions.R")

# Remove temp file
file.remove("make_candidate_failed_invasions.R")


### Build candidate datasets for analysis I, II, and III

source("build_data_sets.R")


### Extract environmental covariate data.

# For simplicity, these are already extracted so they don't need to be run
# source("extract_temperature.R")
# source("extract_snowdepth.R")


### Run analysis I

# NOTE: It likely doesn't make sense to RUNALL this analysis as there is a lot going on
# Will likely want to run analyses separately
source("analysisI_failed_invasion.R")

### Run analysis II

source("analysisII_decline.R")


### Run analysis III

knitr::purl("analysisIII_infection_load.Rmd")

# Source R script
source("analysisIII_infection_load.R")

# Remove temp file
file.remove("analysisIII_infection_load.R")

